// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: no/no.proto

package nov1

import (
	common "github.com/budka-tech/snip-common-go/contract/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadArticleParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadArticleParams) Reset() {
	*x = UploadArticleParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_no_no_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadArticleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArticleParams) ProtoMessage() {}

func (x *UploadArticleParams) ProtoReflect() protoreflect.Message {
	mi := &file_no_no_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArticleParams.ProtoReflect.Descriptor instead.
func (*UploadArticleParams) Descriptor() ([]byte, []int) {
	return file_no_no_proto_rawDescGZIP(), []int{0}
}

type Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceSlug string `protobuf:"bytes,2,opt,name=source_slug,json=sourceSlug,proto3" json:"source_slug,omitempty"`
	Lang       int32  `protobuf:"varint,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	PublishAt  string `protobuf:"bytes,6,opt,name=publishAt,proto3" json:"publishAt,omitempty"`
}

func (x *Article) Reset() {
	*x = Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_no_no_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_no_no_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_no_no_proto_rawDescGZIP(), []int{1}
}

func (x *Article) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Article) GetSourceSlug() string {
	if x != nil {
		return x.SourceSlug
	}
	return ""
}

func (x *Article) GetLang() int32 {
	if x != nil {
		return x.Lang
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetPublishAt() string {
	if x != nil {
		return x.PublishAt
	}
	return ""
}

var File_no_no_proto protoreflect.FileDescriptor

var file_no_no_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x6f, 0x2f, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x9c, 0x01, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x61,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x74,
	0x32, 0x44, 0x0a, 0x02, 0x4e, 0x4f, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x78, 0x33, 0x61, 0x2e, 0x6e, 0x6f,
	0x3b, 0x6e, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_no_no_proto_rawDescOnce sync.Once
	file_no_no_proto_rawDescData = file_no_no_proto_rawDesc
)

func file_no_no_proto_rawDescGZIP() []byte {
	file_no_no_proto_rawDescOnce.Do(func() {
		file_no_no_proto_rawDescData = protoimpl.X.CompressGZIP(file_no_no_proto_rawDescData)
	})
	return file_no_no_proto_rawDescData
}

var file_no_no_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_no_no_proto_goTypes = []any{
	(*UploadArticleParams)(nil), // 0: assist.UploadArticleParams
	(*Article)(nil),             // 1: assist.Article
	(*common.Response)(nil),     // 2: common.Response
}
var file_no_no_proto_depIdxs = []int32{
	0, // 0: assist.NO.UploadArticle:input_type -> assist.UploadArticleParams
	2, // 1: assist.NO.UploadArticle:output_type -> common.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_no_no_proto_init() }
func file_no_no_proto_init() {
	if File_no_no_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_no_no_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UploadArticleParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_no_no_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_no_no_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_no_no_proto_goTypes,
		DependencyIndexes: file_no_no_proto_depIdxs,
		MessageInfos:      file_no_no_proto_msgTypes,
	}.Build()
	File_no_no_proto = out.File
	file_no_no_proto_rawDesc = nil
	file_no_no_proto_goTypes = nil
	file_no_no_proto_depIdxs = nil
}
